# Generated by Django 3.0.6 on 2020-05-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.PositiveSmallIntegerField(default=0, max_length=3)),
                ('g', models.PositiveSmallIntegerField(default=0, max_length=3)),
                ('b', models.PositiveSmallIntegerField(default=0, max_length=3)),
                ('a', models.PositiveSmallIntegerField(default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(max_length=3)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leds.Color')),
            ],
        ),
    ]
