# Generated by Django 3.0.6 on 2020-05-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='a',
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='color',
            name='b',
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='color',
            name='g',
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='color',
            name='r',
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
    ]
