# Generated by Django 3.0.6 on 2020-05-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leds', '0003_auto_20200520_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='index',
            field=models.IntegerField(),
        ),
    ]
