# Generated by Django 3.0.6 on 2020-05-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leds', '0006_auto_20200522_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='a',
            field=models.PositiveSmallIntegerField(default=255),
        ),
    ]
