# Generated by Django 3.0.6 on 2020-05-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leds', '0007_auto_20200522_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='a',
        ),
    ]
