# Generated by Django 3.0.6 on 2020-06-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leds', '0008_remove_color_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='leds',
            field=models.ManyToManyField(to='leds.LED'),
        ),
    ]
